kind: Namespace
apiVersion: v1
metadata:
  name: jenkins
---
kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: theta
---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
